cargo-features = ["strip"]

[workspace]
members = [ "encodelib", "exe_tool", "mlt_tool" ]

[profile.dev]
lto = true 
opt-level = 0

[profile.release]
lto = true 
codegen-units = 1 
opt-level = "z"
symbols="strip"
panic='abort'
