cargo-features = ["strip"]

[workspace]
members = [ "encodelib", "exe_tool", "mlt_tool" ]

[profile.dev]
lto = true 
opt-level = 0

[profile.release]
lto = true 
codegen-units = 1    # should be 1, test diff
opt-level = "z"       # is this highest  
symbols="strip"
panic='abort'